vim.wo.number = true
vim.wo.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.o.colorcolumn = "120"
vim.g.autoformat = false
vim.opt.linespace = 5
vim.opt.termguicolors = true
-- vim.o.lazyredraw = true
vim.o.ttyfast = true

vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.showmode = false
vim.opt.smartindent = true
vim.opt.swapfile = false
vim.opt.smartcase = true
vim.opt.showtabline = 0
vim.opt.cursorline = true 
vim.opt.breakindent = true
vim.opt.wrap = true

vim.cmd("let g:netrw_banner = 0 ")
vim.opt.backup = false
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.inccommand = "split"
vim.opt.background = "dark"
vim.opt.scrolloff = 8
vim.opt.signcolumn = "yes"
vim.opt.backspace = { "start", "eol", "indent" }
vim.opt.splitright = true --split vertical window to the right
vim.opt.splitbelow = true --split horizontal window to the bottom
vim.opt.isfname:append("@-@")
vim.opt.updatetime = 50
vim.opt.hlsearch = true
vim.opt.mouse = "a"
vim.g.editorconfig = true
